
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class Qeydiyyat extends javax.swing.JFrame {

    
    public Qeydiyyat() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qeydiyyatEkranıPanel = new javax.swing.JPanel();
        qeydiyyatLabel = new javax.swing.JLabel();
        seriyaLabel = new javax.swing.JLabel();
        adSoyadLabel = new javax.swing.JLabel();
        adSoyadText = new javax.swing.JTextField();
        seriyaText = new javax.swing.JTextField();
        qeydiyyatButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        qeydiyyatEkranıPanel.setBackground(new java.awt.Color(255, 204, 204));

        qeydiyyatLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        qeydiyyatLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qeydiyyatLabel.setText("Qeydiyyata Xoş Gəldiniz");

        seriyaLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        seriyaLabel.setText("Seriya No :");

        adSoyadLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adSoyadLabel.setText("Ad Soyad :");

        adSoyadText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        adSoyadText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adSoyadTextActionPerformed(evt);
            }
        });

        seriyaText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        qeydiyyatButton.setText("Qeydiyyat");
        qeydiyyatButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        qeydiyyatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qeydiyyatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout qeydiyyatEkranıPanelLayout = new javax.swing.GroupLayout(qeydiyyatEkranıPanel);
        qeydiyyatEkranıPanel.setLayout(qeydiyyatEkranıPanelLayout);
        qeydiyyatEkranıPanelLayout.setHorizontalGroup(
            qeydiyyatEkranıPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qeydiyyatEkranıPanelLayout.createSequentialGroup()
                .addGroup(qeydiyyatEkranıPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(seriyaText, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(qeydiyyatEkranıPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(qeydiyyatEkranıPanelLayout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addGroup(qeydiyyatEkranıPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(seriyaLabel)
                                .addComponent(adSoyadLabel))
                            .addGap(56, 56, 56))
                        .addGroup(qeydiyyatEkranıPanelLayout.createSequentialGroup()
                            .addGap(178, 178, 178)
                            .addComponent(adSoyadText, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(qeydiyyatEkranıPanelLayout.createSequentialGroup()
                            .addGap(140, 140, 140)
                            .addComponent(qeydiyyatLabel))))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, qeydiyyatEkranıPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(qeydiyyatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );
        qeydiyyatEkranıPanelLayout.setVerticalGroup(
            qeydiyyatEkranıPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qeydiyyatEkranıPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(qeydiyyatLabel)
                .addGap(55, 55, 55)
                .addGroup(qeydiyyatEkranıPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adSoyadText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adSoyadLabel))
                .addGap(29, 29, 29)
                .addGroup(qeydiyyatEkranıPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seriyaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seriyaLabel))
                .addGap(26, 26, 26)
                .addComponent(qeydiyyatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(qeydiyyatEkranıPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(qeydiyyatEkranıPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adSoyadTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adSoyadTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adSoyadTextActionPerformed

    private void qeydiyyatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qeydiyyatButtonActionPerformed
        JOptionPane.showMessageDialog(this, "Qeydiyyat : Uğurlu");
        ActionAyarlar.setVisible(this, new MainMenu());
    }//GEN-LAST:event_qeydiyyatButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Qeydiyyat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Qeydiyyat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Qeydiyyat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Qeydiyyat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Qeydiyyat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adSoyadLabel;
    private javax.swing.JTextField adSoyadText;
    private javax.swing.JButton qeydiyyatButton;
    private javax.swing.JPanel qeydiyyatEkranıPanel;
    private javax.swing.JLabel qeydiyyatLabel;
    private javax.swing.JLabel seriyaLabel;
    private javax.swing.JTextField seriyaText;
    // End of variables declaration//GEN-END:variables
}
